unqNumbers = set()
theNum = input('Enter the number : ')
unqNumbers.add(theNum)
theNum = input('Enter the number : ')
unqNumbers.add(theNum)
theNum = input('Enter the number : ')
unqNumbers.add(theNum)
theNum = input('Enter the number : ')
unqNumbers.add(theNum)
theNum = input('Enter the number : ')
unqNumbers.add(theNum)
theNum = input('Enter the number : ')
unqNumbers.add(theNum)
theNum = input('Enter the number : ')
unqNumbers.add(theNum)
theNum = input('Enter the number : ')
unqNumbers.add(theNum)

print(unqNumbers)